# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 393)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Pictures/ros-kinetic.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setObjectName("submitButton")
        self.gridLayout.addWidget(self.submitButton, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.credit_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.credit_1.setObjectName("credit_1")
        self.gridLayout_2.addWidget(self.credit_1, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 7, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        self.credit_6 = QtWidgets.QSpinBox(self.centralwidget)
        self.credit_6.setObjectName("credit_6")
        self.gridLayout_2.addWidget(self.credit_6, 6, 2, 1, 1)
        self.label_credit_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_credit_4.setFont(font)
        self.label_credit_4.setObjectName("label_credit_4")
        self.gridLayout_2.addWidget(self.label_credit_4, 4, 1, 1, 1)
        self.grade_5 = QtWidgets.QComboBox(self.centralwidget)
        self.grade_5.setObjectName("grade_5")
        self.grade_5.addItem("")
        self.grade_5.setItemText(0, "")
        self.grade_5.addItem("")
        self.grade_5.addItem("")
        self.grade_5.addItem("")
        self.grade_5.addItem("")
        self.grade_5.addItem("")
        self.grade_5.addItem("")
        self.grade_5.addItem("")
        self.grade_5.addItem("")
        self.gridLayout_2.addWidget(self.grade_5, 5, 5, 1, 1)
        self.label_grade_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_grade_3.setFont(font)
        self.label_grade_3.setObjectName("label_grade_3")
        self.gridLayout_2.addWidget(self.label_grade_3, 3, 4, 1, 1)
        self.grade_4 = QtWidgets.QComboBox(self.centralwidget)
        self.grade_4.setObjectName("grade_4")
        self.grade_4.addItem("")
        self.grade_4.setItemText(0, "")
        self.grade_4.addItem("")
        self.grade_4.addItem("")
        self.grade_4.addItem("")
        self.grade_4.addItem("")
        self.grade_4.addItem("")
        self.grade_4.addItem("")
        self.grade_4.addItem("")
        self.grade_4.addItem("")
        self.gridLayout_2.addWidget(self.grade_4, 4, 5, 1, 1)
        self.credit_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.credit_2.setObjectName("credit_2")
        self.gridLayout_2.addWidget(self.credit_2, 1, 2, 1, 1)
        self.grade_2 = QtWidgets.QComboBox(self.centralwidget)
        self.grade_2.setObjectName("grade_2")
        self.grade_2.addItem("")
        self.grade_2.setItemText(0, "")
        self.grade_2.addItem("")
        self.grade_2.addItem("")
        self.grade_2.addItem("")
        self.grade_2.addItem("")
        self.grade_2.addItem("")
        self.grade_2.addItem("")
        self.grade_2.addItem("")
        self.grade_2.addItem("")
        self.gridLayout_2.addWidget(self.grade_2, 1, 5, 1, 1)
        self.grade_8 = QtWidgets.QComboBox(self.centralwidget)
        self.grade_8.setObjectName("grade_8")
        self.grade_8.addItem("")
        self.grade_8.setItemText(0, "")
        self.grade_8.addItem("")
        self.grade_8.addItem("")
        self.grade_8.addItem("")
        self.grade_8.addItem("")
        self.grade_8.addItem("")
        self.grade_8.addItem("")
        self.grade_8.addItem("")
        self.grade_8.addItem("")
        self.gridLayout_2.addWidget(self.grade_8, 8, 5, 1, 1)
        self.label_credit_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_credit_3.setFont(font)
        self.label_credit_3.setObjectName("label_credit_3")
        self.gridLayout_2.addWidget(self.label_credit_3, 3, 1, 1, 1)
        self.credit_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.credit_5.setObjectName("credit_5")
        self.gridLayout_2.addWidget(self.credit_5, 5, 2, 1, 1)
        self.label_grade_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_grade_2.setFont(font)
        self.label_grade_2.setObjectName("label_grade_2")
        self.gridLayout_2.addWidget(self.label_grade_2, 1, 4, 1, 1)
        self.grade_3 = QtWidgets.QComboBox(self.centralwidget)
        self.grade_3.setObjectName("grade_3")
        self.grade_3.addItem("")
        self.grade_3.setItemText(0, "")
        self.grade_3.addItem("")
        self.grade_3.addItem("")
        self.grade_3.addItem("")
        self.grade_3.addItem("")
        self.grade_3.addItem("")
        self.grade_3.addItem("")
        self.grade_3.addItem("")
        self.grade_3.addItem("")
        self.gridLayout_2.addWidget(self.grade_3, 3, 5, 1, 1)
        self.grade_7 = QtWidgets.QComboBox(self.centralwidget)
        self.grade_7.setObjectName("grade_7")
        self.grade_7.addItem("")
        self.grade_7.setItemText(0, "")
        self.grade_7.addItem("")
        self.grade_7.addItem("")
        self.grade_7.addItem("")
        self.grade_7.addItem("")
        self.grade_7.addItem("")
        self.grade_7.addItem("")
        self.grade_7.addItem("")
        self.grade_7.addItem("")
        self.gridLayout_2.addWidget(self.grade_7, 7, 5, 1, 1)
        self.label_credit_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_credit_8.setFont(font)
        self.label_credit_8.setObjectName("label_credit_8")
        self.gridLayout_2.addWidget(self.label_credit_8, 8, 1, 1, 1)
        self.label_grade_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_grade_5.setFont(font)
        self.label_grade_5.setObjectName("label_grade_5")
        self.gridLayout_2.addWidget(self.label_grade_5, 5, 4, 1, 1)
        self.label_grade_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_grade_1.setFont(font)
        self.label_grade_1.setObjectName("label_grade_1")
        self.gridLayout_2.addWidget(self.label_grade_1, 0, 4, 1, 1)
        self.grade_1 = QtWidgets.QComboBox(self.centralwidget)
        self.grade_1.setObjectName("grade_1")
        self.grade_1.addItem("")
        self.grade_1.setItemText(0, "")
        self.grade_1.addItem("")
        self.grade_1.addItem("")
        self.grade_1.addItem("")
        self.grade_1.addItem("")
        self.grade_1.addItem("")
        self.grade_1.addItem("")
        self.grade_1.addItem("")
        self.grade_1.addItem("")
        self.gridLayout_2.addWidget(self.grade_1, 0, 5, 1, 1)
        self.label_grade_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_grade_4.setFont(font)
        self.label_grade_4.setObjectName("label_grade_4")
        self.gridLayout_2.addWidget(self.label_grade_4, 4, 4, 1, 1)
        self.credit_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.credit_4.setObjectName("credit_4")
        self.gridLayout_2.addWidget(self.credit_4, 4, 2, 1, 1)
        self.label_grade_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_grade_8.setFont(font)
        self.label_grade_8.setObjectName("label_grade_8")
        self.gridLayout_2.addWidget(self.label_grade_8, 8, 4, 1, 1)
        self.label_credit_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_credit_5.setFont(font)
        self.label_credit_5.setObjectName("label_credit_5")
        self.gridLayout_2.addWidget(self.label_credit_5, 5, 1, 1, 1)
        self.label_credit_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_credit_7.setFont(font)
        self.label_credit_7.setObjectName("label_credit_7")
        self.gridLayout_2.addWidget(self.label_credit_7, 7, 1, 1, 1)
        self.label_credit_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_credit_1.setFont(font)
        self.label_credit_1.setObjectName("label_credit_1")
        self.gridLayout_2.addWidget(self.label_credit_1, 0, 1, 1, 1)
        self.label_credit_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_credit_2.setFont(font)
        self.label_credit_2.setObjectName("label_credit_2")
        self.gridLayout_2.addWidget(self.label_credit_2, 1, 1, 1, 1)
        self.credit_8 = QtWidgets.QSpinBox(self.centralwidget)
        self.credit_8.setObjectName("credit_8")
        self.gridLayout_2.addWidget(self.credit_8, 8, 2, 1, 1)
        self.credit_7 = QtWidgets.QSpinBox(self.centralwidget)
        self.credit_7.setObjectName("credit_7")
        self.gridLayout_2.addWidget(self.credit_7, 7, 2, 1, 1)
        self.label_credit_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_credit_6.setFont(font)
        self.label_credit_6.setObjectName("label_credit_6")
        self.gridLayout_2.addWidget(self.label_credit_6, 6, 1, 1, 1)
        self.label_grade_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_grade_6.setFont(font)
        self.label_grade_6.setObjectName("label_grade_6")
        self.gridLayout_2.addWidget(self.label_grade_6, 6, 4, 1, 1)
        self.grade_6 = QtWidgets.QComboBox(self.centralwidget)
        self.grade_6.setObjectName("grade_6")
        self.grade_6.addItem("")
        self.grade_6.setItemText(0, "")
        self.grade_6.addItem("")
        self.grade_6.addItem("")
        self.grade_6.addItem("")
        self.grade_6.addItem("")
        self.grade_6.addItem("")
        self.grade_6.addItem("")
        self.grade_6.addItem("")
        self.grade_6.addItem("")
        self.gridLayout_2.addWidget(self.grade_6, 6, 5, 1, 1)
        self.credit_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.credit_3.setObjectName("credit_3")
        self.gridLayout_2.addWidget(self.credit_3, 3, 2, 1, 1)
        self.label_grade_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_grade_7.setFont(font)
        self.label_grade_7.setObjectName("label_grade_7")
        self.gridLayout_2.addWidget(self.label_grade_7, 7, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 6, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 6, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 6, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 4, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 5, 3, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 3, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 8, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 5, 6, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 6, 6, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 8, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 4, 6, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 3, 6, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 1, 6, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 7, 3, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem22, 7, 6, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem23, 8, 6, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_total_credits = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_total_credits.setFont(font)
        self.label_total_credits.setObjectName("label_total_credits")
        self.horizontalLayout_7.addWidget(self.label_total_credits)
        self.total_credits = QtWidgets.QSpinBox(self.centralwidget)
        self.total_credits.setObjectName("total_credits")
        self.horizontalLayout_7.addWidget(self.total_credits)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem24)
        self.label_current_gpa = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_gpa.setFont(font)
        self.label_current_gpa.setObjectName("label_current_gpa")
        self.horizontalLayout_7.addWidget(self.label_current_gpa)
        self.current_gpa = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.current_gpa.setObjectName("current_gpa")
        self.horizontalLayout_7.addWidget(self.current_gpa)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.grade_5.setCurrentIndex(0)
        self.grade_4.setCurrentIndex(0)
        self.grade_2.setCurrentIndex(0)
        self.grade_8.setCurrentIndex(0)
        self.grade_3.setCurrentIndex(0)
        self.grade_7.setCurrentIndex(0)
        self.grade_1.setCurrentIndex(0)
        self.grade_6.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.credit_1, self.grade_1)
        MainWindow.setTabOrder(self.grade_1, self.credit_2)
        MainWindow.setTabOrder(self.credit_2, self.grade_2)
        MainWindow.setTabOrder(self.grade_2, self.credit_3)
        MainWindow.setTabOrder(self.credit_3, self.grade_3)
        MainWindow.setTabOrder(self.grade_3, self.credit_4)
        MainWindow.setTabOrder(self.credit_4, self.grade_4)
        MainWindow.setTabOrder(self.grade_4, self.credit_5)
        MainWindow.setTabOrder(self.credit_5, self.grade_5)
        MainWindow.setTabOrder(self.grade_5, self.credit_6)
        MainWindow.setTabOrder(self.credit_6, self.grade_6)
        MainWindow.setTabOrder(self.grade_6, self.credit_7)
        MainWindow.setTabOrder(self.credit_7, self.grade_7)
        MainWindow.setTabOrder(self.grade_7, self.credit_8)
        MainWindow.setTabOrder(self.credit_8, self.grade_8)
        MainWindow.setTabOrder(self.grade_8, self.submitButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUI"))
        self.submitButton.setText(_translate("MainWindow", "Calculate"))
        self.label_credit_4.setText(_translate("MainWindow", "Credit :"))
        self.grade_5.setItemText(1, _translate("MainWindow", "AA"))
        self.grade_5.setItemText(2, _translate("MainWindow", "BA"))
        self.grade_5.setItemText(3, _translate("MainWindow", "BB"))
        self.grade_5.setItemText(4, _translate("MainWindow", "CB"))
        self.grade_5.setItemText(5, _translate("MainWindow", "CC"))
        self.grade_5.setItemText(6, _translate("MainWindow", "DC"))
        self.grade_5.setItemText(7, _translate("MainWindow", "DD"))
        self.grade_5.setItemText(8, _translate("MainWindow", "FF"))
        self.label_grade_3.setText(_translate("MainWindow", "Grade :"))
        self.grade_4.setItemText(1, _translate("MainWindow", "AA"))
        self.grade_4.setItemText(2, _translate("MainWindow", "BA"))
        self.grade_4.setItemText(3, _translate("MainWindow", "BB"))
        self.grade_4.setItemText(4, _translate("MainWindow", "CB"))
        self.grade_4.setItemText(5, _translate("MainWindow", "CC"))
        self.grade_4.setItemText(6, _translate("MainWindow", "DC"))
        self.grade_4.setItemText(7, _translate("MainWindow", "DD"))
        self.grade_4.setItemText(8, _translate("MainWindow", "FF"))
        self.grade_2.setItemText(1, _translate("MainWindow", "AA"))
        self.grade_2.setItemText(2, _translate("MainWindow", "BA"))
        self.grade_2.setItemText(3, _translate("MainWindow", "BB"))
        self.grade_2.setItemText(4, _translate("MainWindow", "CB"))
        self.grade_2.setItemText(5, _translate("MainWindow", "CC"))
        self.grade_2.setItemText(6, _translate("MainWindow", "DC"))
        self.grade_2.setItemText(7, _translate("MainWindow", "DD"))
        self.grade_2.setItemText(8, _translate("MainWindow", "FF"))
        self.grade_8.setItemText(1, _translate("MainWindow", "AA"))
        self.grade_8.setItemText(2, _translate("MainWindow", "BA"))
        self.grade_8.setItemText(3, _translate("MainWindow", "BB"))
        self.grade_8.setItemText(4, _translate("MainWindow", "CB"))
        self.grade_8.setItemText(5, _translate("MainWindow", "CC"))
        self.grade_8.setItemText(6, _translate("MainWindow", "DC"))
        self.grade_8.setItemText(7, _translate("MainWindow", "DD"))
        self.grade_8.setItemText(8, _translate("MainWindow", "FF"))
        self.label_credit_3.setText(_translate("MainWindow", "Credit :"))
        self.label_grade_2.setText(_translate("MainWindow", "Grade :"))
        self.grade_3.setItemText(1, _translate("MainWindow", "AA"))
        self.grade_3.setItemText(2, _translate("MainWindow", "BA"))
        self.grade_3.setItemText(3, _translate("MainWindow", "BB"))
        self.grade_3.setItemText(4, _translate("MainWindow", "CB"))
        self.grade_3.setItemText(5, _translate("MainWindow", "CC"))
        self.grade_3.setItemText(6, _translate("MainWindow", "DC"))
        self.grade_3.setItemText(7, _translate("MainWindow", "DD"))
        self.grade_3.setItemText(8, _translate("MainWindow", "FF"))
        self.grade_7.setItemText(1, _translate("MainWindow", "AA"))
        self.grade_7.setItemText(2, _translate("MainWindow", "BA"))
        self.grade_7.setItemText(3, _translate("MainWindow", "BB"))
        self.grade_7.setItemText(4, _translate("MainWindow", "CB"))
        self.grade_7.setItemText(5, _translate("MainWindow", "CC"))
        self.grade_7.setItemText(6, _translate("MainWindow", "DC"))
        self.grade_7.setItemText(7, _translate("MainWindow", "DD"))
        self.grade_7.setItemText(8, _translate("MainWindow", "FF"))
        self.label_credit_8.setText(_translate("MainWindow", "Credit :"))
        self.label_grade_5.setText(_translate("MainWindow", "Grade :"))
        self.label_grade_1.setText(_translate("MainWindow", "Grade :"))
        self.grade_1.setItemText(1, _translate("MainWindow", "AA"))
        self.grade_1.setItemText(2, _translate("MainWindow", "BA"))
        self.grade_1.setItemText(3, _translate("MainWindow", "BB"))
        self.grade_1.setItemText(4, _translate("MainWindow", "CB"))
        self.grade_1.setItemText(5, _translate("MainWindow", "CC"))
        self.grade_1.setItemText(6, _translate("MainWindow", "DC"))
        self.grade_1.setItemText(7, _translate("MainWindow", "DD"))
        self.grade_1.setItemText(8, _translate("MainWindow", "FF"))
        self.label_grade_4.setText(_translate("MainWindow", "Grade :"))
        self.label_grade_8.setText(_translate("MainWindow", "Grade :"))
        self.label_credit_5.setText(_translate("MainWindow", "Credit :"))
        self.label_credit_7.setText(_translate("MainWindow", "Credit :"))
        self.label_credit_1.setText(_translate("MainWindow", "Credit :"))
        self.label_credit_2.setText(_translate("MainWindow", "Credit :"))
        self.label_credit_6.setText(_translate("MainWindow", "Credit :"))
        self.label_grade_6.setText(_translate("MainWindow", "Grade :"))
        self.grade_6.setItemText(1, _translate("MainWindow", "AA"))
        self.grade_6.setItemText(2, _translate("MainWindow", "BA"))
        self.grade_6.setItemText(3, _translate("MainWindow", "BB"))
        self.grade_6.setItemText(4, _translate("MainWindow", "CB"))
        self.grade_6.setItemText(5, _translate("MainWindow", "CC"))
        self.grade_6.setItemText(6, _translate("MainWindow", "DC"))
        self.grade_6.setItemText(7, _translate("MainWindow", "DD"))
        self.grade_6.setItemText(8, _translate("MainWindow", "FF"))
        self.label_grade_7.setText(_translate("MainWindow", "Grade :"))
        self.label_total_credits.setText(_translate("MainWindow", "Total Credits :"))
        self.label_current_gpa.setText(_translate("MainWindow", "Current GPA :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

